// Auto-generated by Scripts/generate-build-version.sh — do not edit manually.
enum BuildVersion {
    static let commitHash = "1d661c"
    static let isDirty = true

    static var display: String {
        isDirty ? "\(commitHash)*" : commitHash
    }
}
