#!/bin/bash
# Generates Sources/Nehir/Core/Support/BuildVersion.swift with git commit info.
# Run before building to embed the current commit hash.

set -euo pipefail

cd "$(dirname "$0")/.."

COMMIT_HASH=$(git rev-parse --short=6 HEAD 2>/dev/null || echo "unknown")
DIRTY_FLAG=$(git diff --quiet HEAD 2>/dev/null && echo "false" || echo "true")

cat > Sources/Nehir/Core/Support/BuildVersion.swift << SWIFT
// Auto-generated by Scripts/generate-build-version.sh — do not edit manually.
enum BuildVersion {
    static let commitHash = "$COMMIT_HASH"
    static let isDirty = $DIRTY_FLAG

    static var display: String {
        isDirty ? "\(commitHash)*" : commitHash
    }
}
SWIFT

echo "BuildVersion: ${COMMIT_HASH}$([ "$DIRTY_FLAG" = "true" ] && echo '*' || echo '')"
